### ISSUE TITLE
Implement basic APIs for the GalapagosEditor component

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo-Mobile/CodeMirror-NetLogo#1]

**Comment by CIVITAS-John** [comment]
For `find` and `replace`, we might need to keep what the user previously put in the panel after we finish the operation.

Also, I wonder if someone repeatedly uses `find`, what will happen? Will it cycle across different instances?

**Comment by CIVITAS-John** [comment]
Note that the two requests might be in conflict...

**Comment by wubbalubbadu** [comment]
> Note that the two requests might be in conflict...

Could you elaborate on that? is it find and replace?

**Comment by wubbalubbadu** [comment]
> For `find` and `replace`, we might need to keep what the user previously put in the panel after we finish the operation.
Ok, I'll get rid of the part that clears the fields in the panel.

> Also, I wonder if someone repeatedly uses `find`, what will happen? Will it cycle across different instances?
Yes, both find and replace will cycle across all possible instances and loop through them. Do you want me to add something like findAll or replaceAll?

**Comment by CIVITAS-John** [comment]
I believe you need to record the previous state and replay it when your program is done. You can try it yourself and see.

Yes, they will be needed - especially replaceAll.

**Comment by wubbalubbadu** [comment]
> I believe you need to record the previous state and replay it when your program is done. You can try it yourself and see.

I managed to do this with replaceAll and findAll, and it works too if you click on findNext and replaceNext only once and click on somewhere else to remove selection. The only issue is that if you click on find/replace button and iterating through the keywords a couple of times, the input in the panel will get lost. This is because when calling the replaceNext command from codemirror, the keywords will get selected when iterating and they will get passed in to the panel automatically, overwriting what it was there before.
